DROP TABLE IF EXISTS CATS;

CREATE TABLE CATS (
  CATS_ID int AUTO_INCREMENT  PRIMARY KEY,
  CATS_AGE int NOT NULL,
  CATS_COLOR varchar(100) NOT NULL,
  CATS_NAME varchar(100) NOT NULL,
  CATS_PERSONALITY varchar(100) NOT NULL,
  CATS_OWNER  varchar(100) NOT NULL
);

INSERT INTO `CATS` (`CATS_AGE`, `CATS_COLOR`, `CATS_NAME`, `CATS_PERSONALITY`, `CATS_OWNER`)
VALUES (6, 'calico', 'catita', 'docile', 'vitória');

INSERT INTO `CATS` (`CATS_AGE`, `CATS_COLOR`, `CATS_NAME`, `CATS_PERSONALITY`, `CATS_OWNER`)
VALUES (7, 'black and white', 'sarita', 'scared', 'vitória');
